### ISSUE TITLE
有点酸

### ISSUE THREAD

**Issue by litson** [ElemeFE/bowl#20]
14年底对本地存储缓存代码开始研究；

15年 产出这个东西 https://github.com/litson/Seedjs

介于公司的某些方面限制，没有发扬光大，继而不再继续开发维护；

今天看到被其他团队实现而且发扬光大，心理感觉有点唏嘘，持续关注，加油

**Comment by cdll** [comment]
神似https://github.com/addyosmani/basket.js

**Comment by classicemi** [comment]
@cdll 其实就是受到 basket.js 的启发，当然现在有比 basket.js 做的更好的地方，将来还会有更多实用的功能。

**Comment by litson** [comment]
CORS的资源干脆不支持了；

**Comment by litson** [comment]
一些想法：
CORS的资源干脆不支持了；
手动指定依赖，用起来比较蛋疼；
没有调试模式；
localStorage在safari隐私模式下跑不起来，这里貌似没有封装；
没细看，不知道获取文件是不是"并发下载+串行执行"，看起来好像不是这样子；

好就这样
