### ISSUE TITLE
执行顺序

### ISSUE THREAD

**Issue by darrenCoding** [ElemeFE/bowl#21]
var bowl = new Bowl()
bowl.add([
	  { url: 'dist/vendor.[hash].js', key: 'vendor' },
	  { url: 'dist/app.[hash].js', key: 'app' },
	  { url: 'dist/style.[hash].css', key: 'style' }
])
请问不论这三个文件是以何种方式加载，能保证按顺序执行吗？

**Comment by classicemi** [comment]
@darrenCoding 
如果要保证按顺序执行，需要这样写：
```javascript
bowl.add([
  { url: 'dist/vendor.[hash].js', key: 'vendor' },
  { url: 'dist/app.[hash].js', key: 'app', dependencies: ['vendor'] },
  { url: 'dist/style.[hash].css', key: 'style', dependencies: ['app'] }
])
```
